name: 'Extract ESLint Problems'
description: 'Extract the number of warnings and errors from eslint'
inputs:
  create-default:
    description: 'Create a default eslint config'
    required: false
    default: false
  use-semicolons:
    description: 'When using create-default, whether to use semicolons or not'
    required: false
    default: true
  path:
    description: 'Path to files to scan with eslint, defaults to ./'
    required: false
    default: './'
  ignore:
    description: 'Files to ignore'
    required: false
    default: '[]'
outputs:
  warnings:
    description: 'Number of warnings from scan'
  errors:
    description: 'Number of errors from scan'
  problems:
    description: 'Total number of problems from scan'
  score:
    description: 'Code score'
runs:
  using: 'node16'
  main: 'index.js'